title: "Censorship-Resistant News Sharing and Microblogging - Borker"
description: "Borker Protocol is an application layer protocol for Bitcoin, Dogecoin and similar UTXO-based, transparent blockchains. Borker is open, decentralized, borderless, permissionless, pseudonymous, immutable, and censorship-resistant."
keywords: "censorship-resistant,immutable,decentralized,news,bitcoin,dogecoin,blockchain,"
locale: "en-US"
