title: "Borker Protocol"
description: "Censorship resistant, immutable Twitter clone built on top of Bitcoin, Dogecoin and similar UTXO-based, transparent blockchains"
image: "https://borker.io/assets/images/borker-logo.png"
keywords: "censorship-resistant,immutable,decentralized,news,bitcoin,dogecoin,blockchain,"
locale: "en-US"
twitterCard: "summary"
twitterHandle: "@BorkerProtocol"